---
# These are the default variables common to most controller_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
# controller_hostname: "{{ inventory_hostname }}"
# controller_username: "admin"
# controller_password: ""
# controller_oauthtoken: ""
# controller_config_file: ""
# controller_validate_certs: false
controller_instance_groups: []
# - name: "instance_group_name"  # mandatory
#  new_name: "new_name"  # optional
#  credential: "credential_name"  # optional
#  policy_instance_percentage: 100  # optional, integer percentage
#  policy_instance_minimum: 100  # optional, integer number of instances
#  policy_instance_list: "exact_match_instances"  # optional
#  pod_spec_override: "pod_specfication"  # optional
#  instances: [] # List of instances to assign to group
#  state: # optional, choices: present, absent
# These are the default variables specific to the **** role

controller_configuration_instance_groups_secure_logging: "{{controller_configuration_secure_logging | default('false')}}"
controller_configuration_instance_groups_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_instance_groups_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
...
