---
# These are the default variables common to most controller_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
# controller_hostname: "{{ inventory_hostname }}"
# controller_username: "admin"
# controller_password: ""
# controller_oauthtoken: ""
# controller_config_file: ""
# controller_validate_certs: false

# These are the default variables specific to the license role

# a list of dicts describing Controller credentials
controller_credentials: []
# possible fields
# - name: "cred_name"  # mandatory
#  new_name: "new_name"  # optional
#  description: "some description"  # optional
#  organization: "Default"  # optional (str or org dict with name field)
#  credential_type: "ssh"  # optional, choices: ssh (i.e. Machine), vault, net, scm, aws, vmware, satellite6, cloudforms, gce, azure_rm, openstack, rhv, insights, controller (str or cred type dict with name field)
#  kind:  # deprecated, use credential_type (str or cred type dict with kind field)
#  inputs: {}  # optional, dictionary of input fields
#  user: "owner_name"  # optional, user owning the credential (str or user dict with username field)
#  team: "owner_name"  # optional, team owning the credential (str or group dict with name field)
#  state: present  # optional, choices: present, absent

controller_configuration_credentials_secure_logging: "{{ controller_configuration_secure_logging | default(true) }}"
controller_configuration_credentials_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_credentials_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
...
