---
# These are the default variables common to most controller_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
# controller_hostname: "{{ inventory_hostname }}"
# controller_username: "admin"
# controller_password: ""
# controller_oauthtoken: ""
# controller_config_file: ""
# controller_validate_certs: false

# These are the default variables specific to the notification_templates role

# list of dict to describe Controller notification templates
controller_notifications: []
# possible fields:
# - name: "notif_name"  # mandatory
#  new_name: "new_name"  # optional
#  description: "some description"  # optional
#  organization: "Default"  # optional
#  notification_type:  # optional, choices: email, grafana, irc, mattermost, pagerduty, rocketchat, slack, twilio, webhook
#  messages: {}  # optional, custom messages with keys started, success or error
#  notification_configuration: {}  # optional, configuration file
#  # Deprecated options, replaced by notification_configuration:
#  # account_sid, account_token, channels, client_name, color, from_number,
#  # headers, host, message_from, nickname, notify, password, port, recipients,
#  # sender, server, service_key, subdomain, targets, to_numbers, token, url,
#  # use_ssl, use_tls, username
#  state: present  # optional, choices: present, absent

controller_configuration_notifications_secure_logging: "{{controller_configuration_secure_logging | default('false')}}"
controller_configuration_notifications_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_notifications_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
...
