---
# These are the default variables common to most controller_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
# controller_hostname: "{{ inventory_hostname }}"
# controller_username: "admin"
# controller_password: ""
# controller_oauthtoken: ""
# controller_config_file: ""
# controller_validate_certs: false

# These are the default variables specific to the users role

# list of dicts describing Controller users
controller_user_accounts: []
# possible fields:
# - username: "user_name"  # mandatory
#  password: "redhat"  # optional (write only, will mark task as changed)
#  email: "somebody@dev.null"  # optional
#  first_name: "Jim"  # optional
#  last_name: "Smith"  # optional
#  is_superuser: false  # optional, boolean
#  is_auditor: false  # optional, boolean
#  organization: Default # optional
#  state: present  # optional, choices: present, absent

# if you're too lazy to give your users a password, this is the default they will get
# set this variable to something false and there won't be a default password
controller_user_default_password: "change_me"

controller_configuration_users_secure_logging: "{{controller_configuration_secure_logging | default('true')}}"
controller_configuration_users_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_users_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
...
