---
controller_hosts:
  - name: localhost
    inventory: localhost
    variables:
      some_var: some_val
      ansible_connection: local
  - name: rhel8c.sudo.net
    inventory: Linux servers
    variables:
      some_var: some_val
...
